#!/usr/bin/env zsh

# Set nvm to lazy load
export NVM_LAZY_LOAD=true

# Set nvm to not use
# export NVM_NO_USE=true

# Set nvm to use
# export NVM_AUTO_USE=true

# Symbolic link to the nvm binary
export NVM_SYMLINK_CURRENT=true

# Extra commands to lazy load nvm for
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('nvim')
