#!/usr/bin/env zsh

function _fzf_has() {
    which "$@" >/dev/null 2>&1
}

_fzf_preview() {
    _fzf_preview_pager='cat'
    foolproofPreview='cat {}'
    if _fzf_has bat; then
        _fzf_preview_pager='bat'
        foolproofPreview='([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (eza -1 --color=always {} || (tree -C {} | less))) || echo {} 2>/dev/null | head -n 200'
    fi
    if _fzf_has batcat; then
        _fzf_preview_pager='batcat'
        foolproofPreview='([[ -f {} ]] && (batcat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (eza -1 --color=always {} || (tree -C {} | less))) || echo {} 2>/dev/null | head -n 200'
    fi
    local preview
    [[ "$FZF_PREVIEW_ADVANCED" == true ]] &&
        preview="lessfilter-fzf {}" ||
        preview="$foolproofPreview"
    echo "$preview"
}

# ─── Fzf Configuration ────────────────────────────────────────────────────────

# Uncomment to set the FZF_DEFAULT_COMMAND
export FZF_BASE_COMMAND="fd --strip-cwd-prefix --hidden --follow --exclude '.git' --exclude 'node_modules'"
export FZF_DEFAULT_COMMAND="$FZF_BASE_COMMAND --type f"
export FZF_ALT_C_COMMAND="$FZF_BASE_COMMAND --type d"
export FZF_CTRL_T_COMMAND="${FZF_BASE_COMMAND}"

# ─── Fzf Configuration ─────────────────────────────────────────────

# Path to install fzf binary and script
# export FZF_PATH="${HOME}/.fzf"

export FZF_PREVIEW="$(_fzf_preview)"

# Set any value supported by fzf --preview-window option
export FZF_PREVIEW_WINDOW=':hidden'

# Use less viewer with a pre-processor to display improved previews for a wide range of files.
# This is an opt-in feature.
# export FZF_PREVIEW_ADVANCED=false

# Color scheme for fzf
export FZF_COLOR_SCHEME="--color=fg:#f8f8f2,bg:#22212c,hl:#8aff80,fg+:#f8f8f2,bg+:#454158,hl+:#ffca80,info:#9580ff,prompt:#8aff80,pointer:#ff80bf,marker:#ff80bf,spinner:#ff80bf,header:#80ffea"

fzf_default_opts+=(
    "--layout=reverse"
    "--info=inline"
    "--height=80%"
    "$FZF_COLOR_SCHEME"
    "--prompt='∼ '"
    "--pointer='▶'"
    "--marker='✓'"
    "--bind '?:toggle-preview'"
    "--bind 'ctrl-a:select-all'"
)

_fzf_compgen_dir() {
    eval "$FZF_ALT_C_COMMAND . \"$1\""
}

_fzf_compgen_path() {
    eval "$FZF_BASE_COMMAND . \"$1\""
}

export FZF_DEFAULT_OPTS=$(printf '%s\n' "${fzf_default_opts[@]}")
export FZF_CTRL_T_OPTS="
    --walker-skip .git,node_modules,target
    --preview '${FZF_PREVIEW}'
    --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_ALT_C_OPTS="
    --walker-skip .git,node_modules,target
    --preview 'eza -1 --color=always {}'"

# ─── Fzf-tab Configuration ────────────────────────────────────────────────────

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:z:*' fzf-preview 'eza -1 --color=always $realpath'
# enable preview window for cd
zstyle ':fzf-tab:complete:z:*' fzf-flags --scheme=path
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags ${FZF_COLOR_SCHEME} --bind=tab:accept
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this plugin. See Aloxaf/fzf-tab#455.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

# ─── Cleanup ──────────────────────────────────────────────────────────────────

unset -f _fzf_has
unset -f _fzf_preview
