#!/usr/bin/env zsh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='nvim'
else
    export EDITOR='code -w'
fi
# Alias edit for editor
alias edit='eval $EDITOR'
