#!/usr/bin/env zsh

alias reload="exec zsh"
alias mdn="man -S3js"
alias wtc="curl -s 'http://whatthecommit.com/' | grep '<p>' | cut -c4-"
alias fixql="xattr -d -r com.apple.quarantine ~/Library/QuickLook/"
