set-option -g default-terminal "xterm-256color"
# -- display -------------------------------------------------------------------

set-option -g base-index 1           # start windows numbering at 1
set-window-option -g pane-base-index 1     # make pane numbering consistent with windows

set-window-option -g automatic-rename on   # rename window to reflect current program
set-option -g renumber-windows on    # renumber windows when a window is closed

set-option -g set-titles on          # set-option terminal title
set-option -g set-titles-string '#h ❐ #S ● #I #W'

# move status line to top
set-option -g status-position top

# activity
set-window-option -g monitor-activity on
set-option -g visual-activity off

# -- behavior ------------------------------------------------------------------

# allow keys to pass through to terminal when prefix is pressed
set-option -g allow-passthrough on

# Turn off aggressive resizing, which can cause issues with iTerm2
set-window-option -g aggressive-resize off

# -- user customizations -------------------------------------------------------
# this is the place to override or undo settings

# create session
bind C-c new-session

# kill session
bind C-x confirm-before kill-session

bind -T root F12  \
  set-option prefix None \;\
  set-option key-table off \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S \;\

bind -T off F12 \
  set-option -u prefix \;\
  set-option -u key-table \;\
  refresh-client -S

# clear both screen and history
bind -n C-l send-keys C-l \; run 'sleep 0.1' \; clear-history

# start with mouse mode enabled
set-option -g mouse on

if '[ -n "$SSH_CLIENT" ]' \
  "set-option -g status-position bottom"

bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# -- plugin configuration ------------------------------------------------------

set-option -g @emulate-scroll-for-no-mouse-alternate-buffer "on"

# -- TPM -----------------------------------------------------------------------
# List of plugins
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set-option -g @plugin 'tmux-plugins/tmux-yank'
set-option -g @plugin 'nhdaly/tmux-better-mouse-mode'

# Import Theme
run-shell "~/.tmux/tmux-theme.tmux"

# Bootstrap tpack automatically
if "command -v tpack" \
   "run 'tpack install'"

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
