#!/usr/bin/env zsh

export MANPAGER="/usr/bin/less -s -M +Gg"
# Define colors
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;34m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;45;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[01;36m'    # begin underline
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline
export GROFF_NO_SGR=1                  # for konsole

# Bold and Blinking
# Blink
less_termcap[mb]="${fg_bold[red]}"
# Bold
less_termcap[md]="${fg_bold[blue]}"
# End All
less_termcap[me]="${reset_color}"
# Standout
less_termcap[so]="${fg_bold[red]}"
less_termcap[se]="${reset_color}"
# Underline
less_termcap[us]="${fg_bold[cyan]}"
less_termcap[ue]="${reset_color}"
